[preprocessor.typst-math]

[preprocessor.last-changed]
command = "mdbook-last-changed"
template = "Last change: {date} ([commit]({commit_url}))"
date_format = "%Y-%m-%d"

[output.html]
git-repository-url = "https://github.com/KwachOjunga/into-the-dungeon"
default-theme = "ayu"
preferred-dark-theme = "ayu"
