name: github pages

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    deploy:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v2

            - name: Install mdbook-last-changed preprocessor
              run: cargo install mdbook-last-changed --locked

            - name: Install mdbook-gitinfo preprocessor
              run: cargo install mdbook-gitinfo --locked

            - name: Install mdbook-typst-math preprocessor
              run: cargo install mdbook-typst-math --locked

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v2
              with:
                  fetch-depth: 0
                  mdbook-version: "latest"

            - run: mdbook build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GH_TOKEN_WORKFLOW }}
                  publish_dir: ./book
